### ISSUE TITLE
iOS Bundle Release

### ISSUE THREAD

**Issue by craigcoles** [joltup/react-native-threads#17]
I am experiencing an issue with threads in production/release.

```
2018-01-31 16:27:03.209993+0000 TestApp[72678:38924584] starting Thread (null)
2018-01-31 16:27:03.217 [fatal][tid:main] No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
```

My Threads don't live in the route of the project, they live in `./App/Workers/*.thread.js`. I have also followed the documentation for building `.jsbundle` files and adding them to `./ios`.

In development, everything works as expected:

```
2018-01-31 17:14:34.192937+0000 TestApp[75866:39010763] starting Thread http://localhost:8081/./App/Workers/Test.Generate.thread.bundle?platform=ios&dev=true&minify=false
2018-01-31 17:14:34.193 [info][tid:com.facebook.react.ThreadManagerQueue][RCTCxxBridge.mm:187] Initializing <RCTCxxBridge: 0x6080001b42e0> (parent: <RCTBridge: 0x60c0002a57c0>, executor: (null))
2018-01-31 17:14:34.193265+0000 TestApp[75866:39010763] Initializing <RCTCxxBridge: 0x6080001b42e0> (parent: <RCTBridge: 0x60c0002a57c0>, executor: (null))

```

Am I experiencing this issue because my thread files don't live in the root of the project?

**Comment by craigcoles** [comment]
Problem solved.

I moved the worker files from `./App/Workers/*.thread.js` to the root `./*.thread.js` and then rebuilt the bundles (after amending the locations in the commands also) and it now works as expected in release mode.

Before I close the issue, is that an issue? Should the documentation be updated to say thats where they need to live? Or is it intended for the workers to live anywhere inside the project?

**Comment by Traviskn** [comment]
Hi @craigcoles, sorry you ran into this issue! 

My understanding is that if your `thread.js` file lives in a different folder like `App/Workers/MyWorker.thread.js`, then you will need to re-create that same file structure in the `ios` folder. The path that you pass to the `new Thread('some/path')` is actually the native code filepath, relative to the `ios` folder in the root of your project.  So in this case I believe you would need to open your project in xcode, right click on your root folder and select the "New Group" option to add an "App" folder, then select the "App" folder, right click, select the "New Group" option and create a "Workers" folder, then finally right click on the "Workers" folder and select the "add files to <your project>" option to add your worker js file to the native project.

For android you would create the matching folder structure in the `android/app/src/main/assets/threads` folder of your project.

Let me know if that makes sense or if it still doesn't work for you.  Keeping thread files at the root level definitely keeps things simpler so that you don't need to add too many extra folders in your native `ios` and `android` directories.

**Comment by craigcoles** [comment]
Hi @Traviskn, that makes complete sense! Would it be worthwhile updating the documentation to reflect this, as this wasn't massively clear for me. If so, I don't mind submitting a PR 👍

**Comment by Traviskn** [comment]
Thanks, I've merged your update to the docs!  Let me know if you run into any more issues

**Comment by Escarpe** [comment]
HI!
Have the same issue, when build release version on ios ( debug and android work correctly).
I have typescript in my project and thread.js placed in dist folder.
I add folder to xcode project and dist in ios folder, but error still happend.
![2018-11-02 22 14 44](https://user-images.githubusercontent.com/26823619/47938481-dca13280-deec-11e8-985d-948dc1ac42d9.png)
![2018-11-02 22 15 18](https://user-images.githubusercontent.com/26823619/47938483-e034b980-deec-11e8-8105-49667af5b8ca.png)

**Comment by JamesPJ** [comment]
[Ref](https://github.com/joltup/react-native-threads/issues/17#issuecomment-362394568)
> So in this case I believe you would need to open your project in xcode, right click on your root folder and select the "New Group" option to add an "App" folder, then select the "App" folder, right click, select the "New Group" option and create a "Workers" folder, then finally right click on the "Workers" folder and select the "add files to " option to add your worker js file to the native project.

Without these steps, iOS build will not work. I had issue fetching the worker bundles, after adding the group in xcode, it started working.
